### Get all books (initially empty)
GET http://localhost:8080/books
Accept: application/json

###

### Add a new book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Spring Boot in Action",
  "author": "Craig Walls",
  "price": 29.99,
  "isbn": "9781617292545"
}

###

### Get all books (after adding one)
GET http://localhost:8080/books
Accept: application/json

###

### Add another book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Effective Java",
  "author": "Joshua Bloch",
  "price": 39.99,
  "isbn": "9780134685991"
}

###

### Get a book by ID (ID 1)
GET http://localhost:8080/books/1
Accept: application/json

###

### Get a book by ID (ID 3, should return 404 Not Found)
GET http://localhost:8080/books/3
Accept: application/json

###

### Update a book (ID 1)
PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "Spring Boot in Action (Updated)",
  "author": "Craig Walls",
  "price": 31.99,
  "isbn": "9781617292545"
}

###

### Get all books (after update)
GET http://localhost:8080/books
Accept: application/json

###

### Delete a book (ID 2)
DELETE http://localhost:8080/books/2

###

### Get all books (after deletion)
GET http://localhost:8080/books
Accept: application/json

###

### Try to delete a non-existent book (ID 3, should return 404 Not Found)
DELETE http://localhost:8080/books/3
